### ISSUE TITLE
Event Detail Page: Create main page body

### ISSUE THREAD

**Issue by jonsanders101** [MarcelCutts/pride-london-web-gatsby#9]
The main body of the page where Event text is displayed, [as shown here](https://projects.invisionapp.com/share/XCI5GGXVG2U#/screens/295436390/comments).

**Comment by kiraarghy** [comment]
@jonsanders101 is this closed?

**Comment by jonsanders101** [comment]
@kiraarghy - sorry, I've been AWOL since creating these issues. You or anyone else who's been involved since will be better judges whether this issue has been done.

**Comment by andrico1234** [comment]
I think we've finished the majority of this page, and the rest of the times should be in the backlog! 

Maybe close this one?
